name: Unit and integration tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Install GLPK and CBC
        run: sudo apt install glpk-utils coinor-cbc libglpk-java
      - name: Run tests
        run: mvn install --projects core,glpk --also-make --fail-at-end --batch-mode -Dmatsim.preferLocalDtds=true -DargLine="-Djava.library.path=/usr/lib/x86_64-linux-gnu/jni"
